### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by Jarred-Sumner** [mstange/pdb-addr2line#66]
I have a [300 MB .pdb file](https://github.com/oven-sh/bun/releases/download/bun-v1.1.0/bun-windows-x64-profile.zip) and I tried to use the example to convert stack frame addresses into their source information and it panics:

```rust
❯ RUST_BACKTRACE=1 pdb-addr2line --exe bun.pdb -psfi 0x7ff6d738193b
thread 'main' panicked at /Users/jarred/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pdb-addr2line-0.11.0/examples/pdb-addr2line.rs:14:47:
Failed to parse address: ParseIntError { kind: PosOverflow }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5facb422f8a5a61df515572fe79b02433639d565/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/5facb422f8a5a61df515572fe79b02433639d565/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/5facb422f8a5a61df515572fe79b02433639d565/library/core/src/result.rs:1649:5
   3: pdb_addr2line::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Doing a find-and-replace from `u32` to `u64` and recompiling doesn't compile successfully (though I didn't expect that to work; I know nothing about the .pdb format) 

Is there an easy way to fix this?

For context, the stack frames I'm looking at look like this:
```js
???:?:?: 0x7ff6da7cce7a in ??? (bun.exe)
???:?:?: 0x7ff6da7cdb9c in ??? (bun.exe)
???:?:?: 0x7ff6da64469b in ??? (bun.exe)
???:?:?: 0x7ff6da63b247 in ??? (bun.exe)
???:?:?: 0x7ff6da6353b0 in ??? (bun.exe)
???:?:?: 0x7ff6da6e8ae2 in ??? (bun.exe)
???:?:?: 0x7ff6da4115f5 in ??? (bun.exe)
???:?:?: 0x7ff6dcf93d63 in ??? (bun.exe)
???:?:?: 0x7ffa754d257c in ??? (KERNEL32.DLL)
???:?:?: 0x7ffa76e4aa57 in ??? (ntdll.dll)
```

**Comment by mstange** [comment]
The addresses that pdb-addr2line need expects are RVAs, i.e. addresses relative to the image load address. When you obtain your stack, you also need to obtain the image load addresses for the loaded modules. For example, if you enumerate the modules using `EnumProcessModules`, you each `HMODULE` value is a pointer to the image start, the pointer address is the image load address.
RVAs currently always fit into u32, as far as I know - I think Windows doesn't support binaries with more than 4GB of machine code in them.
The absolute addresses (e.g. 0x7ff6da7cce7a) can change on each run due to ASLR, so feeding those into pdb-addr2line without any information about where modules are loaded could never work.
